---

sql:
  default:
    url: url-dev
    cred: cred-dev

  customer1:
    url: url1-dev
    cred: cred1-dev
  customer2:
    url: url2-dev
    cred: cred2-dev

dynamo:
  default:
    url: url-dynamo-dev
    cred: cred-dev

  customer1:
    url: url1-dynamo-dev
    cred: cred1-dev
  customer2:
    url: url2-dynamo-dev
    cred: cred2-dev