---

sql:
  default:
    url: url-prod
    cred: cred-prod

  customer1:
    url: url1-prod
    cred: cred1-prod
  customer2:
    url: url2-prod
    cred: cred2-prod

dynamo:
  default:
    url: url-dynamo-prod
    cred: cred-prod

  customer1:
    url: url1-dynamo-prod
    cred: cred1-prod
  customer2:
    url: url2-dynamo-prod
    cred: cred2-prod